---
deployment:
  tasks:
    - export DEPLOY_PATH=/home/silkmart/silkmart
    - /usr/bin/pkill -u silkmart -9 -f query-engine || true
    - /usr/bin/pkill -u silkmart -9 -f next-server || true
    - /usr/bin/pkill -u silkmart -9 -f node || true
    - /bin/cp -rf deploy/. $DEPLOY_PATH
    - /usr/bin/touch $DEPLOY_PATH/tmp/restart.txt
