---
deployment:
  tasks:
    - export DEPLOYPATH=/home/silkmart/ctg-collection
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH
    - /usr/bin/npm install
    - /usr/bin/npm run build
    - /usr/bin/touch tmp/restart.txt
